=== carlhuth/openmeetings/xdocs/website.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
      http://www.apache.org/licenses/LICENSE-2.0
    	  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
  
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="document">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="properties"/>
        <xs:element ref="body"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="properties">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="author"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="author">
    <xs:complexType mixed="true">
      <xs:attribute name="email" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="body">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="section"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="section">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="b"/>
        <xs:element ref="br"/>
        <xs:element ref="div"/>
        <xs:element ref="img"/>
        <xs:element ref="object"/>
        <xs:element ref="ol"/>
        <xs:element ref="p"/>
        <xs:element ref="pre"/>
        <xs:element ref="tt"/>
        <xs:element ref="ul"/>
        <xs:element ref="feature"/>
        <xs:element ref="source"/>
        <xs:element ref="style"/>
        <xs:element ref="subsection"/>
        <xs:element ref="table"/>
      </xs:choice>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="feature">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="image"/>
        <xs:element ref="text"/>
      </xs:sequence>
      <xs:attribute name="title" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="image">
    <xs:complexType>
      <xs:attribute name="fullhref" use="required"/>
      <xs:attribute name="height" type="xs:integer"/>
      <xs:attribute name="href" use="required"/>
      <xs:attribute name="title" use="required"/>
      <xs:attribute name="width" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="text">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="div"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="source">
    <xs:complexType mixed="true">
      <xs:attribute name="test" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="style">
  </xs:element>
  <xs:element name="subsection">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="i"/>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="div"/>
            <xs:element ref="ol"/>
            <xs:element ref="p"/>
            <xs:element ref="pre"/>
          </xs:choice>
        </xs:choice>
        <xs:element minOccurs="0" ref="ul"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="tr"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tr">
    <xs:complexType>
      <xs:choice>
        <xs:element maxOccurs="unbounded" ref="th"/>
        <xs:element maxOccurs="unbounded" ref="td"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="th">
    <xs:complexType mixed="true">
      <xs:attribute name="style"/>
      <xs:attribute name="class"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="td">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="p"/>
        <xs:element ref="b"/>
      </xs:choice>
      <xs:attribute name="style"/>
      <xs:attribute name="class"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ul">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="li"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="b">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="i">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="b"/>
        <xs:element ref="br"/>
        <xs:element ref="tt"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="b"/>
        <xs:element ref="br"/>
        <xs:element ref="div"/>
        <xs:element ref="i"/>
        <xs:element ref="strong"/>
        <xs:element ref="tt"/>
        <xs:element ref="em"/>
      </xs:choice>
      <xs:attribute name="style"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="em" type="xs:string"/>
  <xs:element name="pre" type="xs:string"/>
  <xs:element name="ol">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="li"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="div">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="b"/>
        <xs:element ref="blockquote"/>
        <xs:element ref="br"/>
        <xs:element ref="div"/>
        <xs:element ref="i"/>
        <xs:element ref="object"/>
        <xs:element ref="ol"/>
        <xs:element ref="p"/>
        <xs:element ref="pre"/>
        <xs:element ref="span"/>
        <xs:element ref="strong"/>
        <xs:element ref="tt"/>
        <xs:element ref="ul"/>
      </xs:choice>
      <xs:attribute name="class" type="xs:NCName"/>
      <xs:attribute name="id" type="xs:NCName"/>
      <xs:attribute name="style" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="a">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="img"/>
        <xs:element ref="span"/>
      </xs:choice>
      <xs:attribute name="class" type="xs:NCName"/>
      <xs:attribute name="href" use="required" type="xs:anyURI"/>
      <xs:attribute name="rel" type="xs:NCName"/>
      <xs:attribute name="target" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="img">
    <xs:complexType>
      <xs:attribute name="alt" use="required"/>
      <xs:attribute name="class" type="xs:NCName"/>
      <xs:attribute name="height" type="xs:integer"/>
      <xs:attribute name="src" use="required"/>
      <xs:attribute name="title"/>
      <xs:attribute name="width" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="object">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="param"/>
        <xs:element ref="embed"/>
      </xs:sequence>
      <xs:attribute name="style" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="param">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="value" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="embed">
    <xs:complexType>
      <xs:attribute name="allowScriptAccess" use="required" type="xs:NCName"/>
      <xs:attribute name="allowfullscreen" use="required" type="xs:boolean"/>
      <xs:attribute name="height" use="required" type="xs:integer"/>
      <xs:attribute name="src" use="required" type="xs:anyURI"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="width" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="br">
    <xs:complexType/>
  </xs:element>
  <xs:element name="tt">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="li">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="b"/>
        <xs:element ref="blockquote"/>
        <xs:element ref="br"/>
        <xs:element ref="div"/>
        <xs:element ref="i"/>
        <xs:element ref="img"/>
        <xs:element ref="ol"/>
        <xs:element ref="p"/>
        <xs:element ref="span"/>
        <xs:element ref="strong"/>
        <xs:element ref="tt"/>
        <xs:element ref="ul"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="strong">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="tt"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="blockquote">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="a"/>
        <xs:element ref="br"/>
        <xs:element ref="i"/>
        <xs:element ref="tt"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="span">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="br"/>
      </xs:choice>
      <xs:attribute name="style"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== carlhuth/openmeetings/xdocs/GeneralConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 -->
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="website.xsd">

	<properties>
		<title>List of general configuration options</title>
		<author email="sebawagner@apache.org">
			OpenMeetings Team
		</author>
	</properties>

	<body>

		<section name="List of general configuration options">
			<style><!--
				.configCell {
					border: 1px solid rgb(204, 204, 204);
					padding: 5px;
				}
			--></style>
			<p>In Administration &gt; Configuration there are a number of
				configuration values.
			</p>
			<p></p>
			<table>
				<tr>
					<th class="configCell"> key </th>
					<th class="configCell"> default </th>
					<th class="configCell"> meaning </th>
					<th class="configCell"> availabe since OpenMeetings version </th>
				</tr>
				<tr>
					<td class="configCell"> user.login.minimum.length </td>
					<td class="configCell"> 4 </td>
					<td class="configCell"> minimum chars required for the login to create a user </td>
					<td class="configCell"> 1.9.x </td>
				</tr>
				<tr>
					<td class="configCell"> user.pass.minimum.length </td>
					<td class="configCell"> 4 </td>
					<td class="configCell"> minimum chars required for the password to create a
						user
					</td>
					<td class="configCell"> 1.9.x </td>
				</tr>
				<tr>
					<td class="configCell"> number.minutes.reminder.send </td>
					<td class="configCell"> 15 </td>
					<td class="configCell"> minutes the one-time reminder in the calender is
						send, set to 0 to disable reminder
					</td>
					<td class="configCell"> 1.9.x </td>
				</tr>
				<tr>
					<td class="configCell"> max_upload_size </td>
					<td class="configCell"> 1073741824 </td>
					<td class="configCell"> Maximum size of upload file (bytes) 1073741824 bytes
						= 1GB
					</td>
					<td class="configCell"> 1.8.x </td>
				</tr>
				<tr>
					<td class="configCell"> show.whiteboard.draw.status </td>
					<td class="configCell"> 0 </td>
					<td class="configCell"> Display name of the user who draw the current object
						(User Name auto-disapper after 3 seconds.
					</td>
					<td class="configCell"> 1.8.x </td>
				</tr>
				<tr>
					<td class="configCell"> use.old.style.ffmpeg.map.option </td>
					<td class="configCell"> 0 </td>
					<td class="configCell"> If the system should "." (old ffmpeg) instead of ":"
						(new ffmpeg) for the -map option in FFMPEG
					</td>
					<td class="configCell"> 1.9.x </td>

				</tr>
				<tr>
					<td class="configCell"> inviter.email.as.replyto </td>
					<td class="configCell"> 1 </td>
					<td class="configCell"> Set inviter's email address as ReplyTo in email invitations (1 == set, 0 == NOT set)	</td>
					<td class="configCell"> 2.0.x </td>
				</tr>
				<tr>
					<td class="configCell"> office.path </td>
					<td class="configCell"> </td>
					<td class="configCell"> The path to OpenOffice/LibreOffice (optional) please set this to the real path in case jodconverter is unable to find OpenOffice/LibreOffice installation automatically	</td>
					<td class="configCell"> 2.0.x </td>
				</tr>
				<tr>
					<td class="configCell"> default.landing.zone </td>
					<td class="configCell"> user/dashboard </td>
					<td class="configCell"> Area to be shown to the user after login. Possible values are: user/dashboard, user/calendar, user/record, rooms/my, rooms/group, rooms/public, admin/user, admin/connection
						, admin/group, admin/room, admin/config, admin/lang, admin/ldap, admin/backup, admin/server, admin/oauth2 </td>
					<td class="configCell"> 2.1.x, <b> values are changed in 3.0.0</b> </td>
				</tr>
				<tr>
					<td class="configCell"> sms.provider </td>
					<td class="configCell">  </td>
					<td class="configCell"> SMS service provider (bulksms.http.1) </td>
					<td class="configCell"> 2.1.x </td>
				</tr>
				<tr>
					<td class="configCell"> sms.Username </td>
					<td class="configCell">  </td>
					<td class="configCell"> Login for SMS service provider </td>
					<td class="configCell"> 2.1.x </td>
				</tr>
				<tr>
					<td class="configCell"> sms.Userpass </td>
					<td class="configCell">  </td>
					<td class="configCell"> Password for SMS service provider </td>
					<td class="configCell"> 2.1.x </td>
				</tr>
				<tr>
					<td class="configCell"> sms.subject </td>
					<td class="configCell">  </td>
					<td class="configCell"> Subject of SMS reminder message </td>
					<td class="configCell"> 2.1.x </td>
				</tr>
				<tr>
					<td class="configCell"> swftools_zoom </td>
					<td class="configCell"> 100 </td>
					<td class="configCell"> DPI for conversion of PDF to SWF (should be an integer between 50 and  600 with a default value of 100 DPI) </td>
					<td class="configCell"> 2.0.x </td>
				</tr>
				<tr>
					<td class="configCell"> swftools_jpegquality </td>
					<td class="configCell"> 85 </td>
					<td class="configCell"> Compression quality for conversion of PDF to SWF (should be an integer between 1 and 100, with a default value of 85) </td>
					<td class="configCell"> 2.0.x </td>
				</tr>
				<tr>
					<td class="configCell"> sendEmailAtRegister </td>
					<td class="configCell"> 0 </td>
					<td class="configCell"> User get a EMail with their Account data. Values: 0(No) or 1(Yes) </td>
					<td class="configCell"> 2.0.x </td>
				</tr>
				<tr>
					<td class="configCell"> sendEmailWithVerficationCode </td>
					<td class="configCell"> 0 </td>
					<td class="configCell"> User must activate their account by clicking on the 
								activation-link in the registering Email. Values: 0(No) or 1(Yes) 
								It makes no sense to make this(sendEmailWithVerficationCode) 1(Yes) while 
								sendEmailAtRegister is 0(No) cause you need
								to send a EMail. </td>
					<td class="configCell"> 2.0.x </td>
				</tr>
				<tr>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> redirect.url.for.external.users </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;">  </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> Users entered the room via invitationHash or secureHash will be redirected to this URL on connection lost </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> 2.2.x </td>
				</tr>
				<tr>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> allow_frontend_register </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> (configurable during install) </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> Is user register available on login screen </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> 1.8.x </td>
				</tr>
				<tr>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> allow.soap.register </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> 1 </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> Is user register available via SOAP/REST </td>
					<td style="border: 1px solid rgb(204, 204, 204); padding: 5px;"> 3.0.x </td>
				</tr>
			</table>
		</section>

	</body>

</document>
